name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  run-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check for duplicated file names
        run: |
          git ls-files --exclude-standard --others --cached --no-empty-directory | sort -f > files.txt
          uniq -di files.txt > duplicates.txt
          if [[ -s duplicates.txt ]]; then
            echo "Found files with the same name:"
            cat duplicates.txt
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Prepare Jenkins data
        run: |
          cat ${{ github.workspace }}/_jenkins_data/jenkins_backup.tar.gz.part_* > ${{ github.workspace }}/jenkins_backup.tar.gz
          md5sum ${{ github.workspace }}/jenkins_backup.tar.gz

      - name: Extract Jenkins data and set permission
        run: |
          tar -xvf ./jenkins_backup.tar.gz
          chmod -R 777 ./jenkins_backup/var/jenkins_home

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker start
        run: docker run --rm --detach -p 8080:8080 -p 50000:50000 -v ${{ github.workspace }}/jenkins_backup/var/jenkins_home:/var/jenkins_home jenkins/jenkins:2.516.3-lts-jdk21

      - name: Wait for the Jenkins
        run: ./.github/wait-for-jenkins.sh

      - name: Run Playwright tests
        run: npm test
        env:
          LOCAL_USERNAME: ${{ secrets.LOCAL_USERNAME}}
          LOCAL_PASSWORD: ${{ secrets.LOCAL_PASSWORD}}
          LOCAL_HOST: ${{ secrets.LOCAL_HOST}}
          LOCAL_PORT: ${{ secrets.LOCAL_PORT}}
          CI_RUN: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Attach artifacts on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Artifacts
          path: test-results/  